#!/usr/bin/env python3
"""Build compact, deterministic maps without reading vault note bodies."""

from __future__ import annotations

import os
from pathlib import Path
import stat
import sys
import tempfile
import time


BEYIN_DIR = Path(__file__).resolve().parent
if str(BEYIN_DIR) not in sys.path:
    sys.path.insert(0, str(BEYIN_DIR))
SCRIPTS_DIR = (BEYIN_DIR / "scripts") if (BEYIN_DIR / "scripts").is_dir() else (BEYIN_DIR.parent / "scripts")
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))
REPO_SCRIPTS = (BEYIN_DIR.parent / "runtime" / "scripts") if (BEYIN_DIR.parent / "runtime" / "scripts").is_dir() else (BEYIN_DIR / "scripts")
if REPO_SCRIPTS.is_dir() and str(REPO_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(REPO_SCRIPTS))

import runtime_platform

try:
    from legacy_names import LEGACY_MAP_HEADER
except ImportError:
    LEGACY_MAP_HEADER = None


COMMAND_CENTER = "🎯 100-Command-Center"
VAULT_MAP = "Vault-Map.md"
SKILLS_MAP = "Skills-Map.md"
EXCLUDED_TOP_LEVEL = {
    ".agents",
    ".beyin",
    ".claude",
    ".codex",
    ".cursor",
    ".git",
    "daily",
    "knowledge",
}
EXCLUDED_NAMES = {".DS_Store", "__pycache__", "backups", ".state"}
GENERATED_MAP_NAMES = {VAULT_MAP, SKILLS_MAP}
HEADER = "<!-- GENERATED BY RESPECTED: manual edits will be replaced. -->\n"


def _safe_entry(path: Path) -> bool:
    try:
        metadata = path.lstat()
    except OSError:
        return False
    return not stat.S_ISLNK(metadata.st_mode) and (
        stat.S_ISDIR(metadata.st_mode) or stat.S_ISREG(metadata.st_mode)
    )


def _visible_paths(vault_root: Path) -> list[str]:
    paths: list[str] = []
    for top in sorted(vault_root.iterdir(), key=lambda item: item.name.casefold()):
        if top.name in EXCLUDED_TOP_LEVEL or top.name in EXCLUDED_NAMES or top.name.startswith("."):
            continue
        if not _safe_entry(top):
            continue
        paths.append(top.relative_to(vault_root).as_posix())
        if not top.is_dir():
            continue
        for child in sorted(top.iterdir(), key=lambda item: item.name.casefold()):
            if (
                child.name in EXCLUDED_NAMES
                or child.name in GENERATED_MAP_NAMES
                or child.name.startswith(".")
                or not _safe_entry(child)
            ):
                continue
            paths.append(child.relative_to(vault_root).as_posix())
            if child.is_dir():
                for grandchild in sorted(child.iterdir(), key=lambda item: item.name.casefold()):
                    if (
                        grandchild.name in EXCLUDED_NAMES
                        or grandchild.name.startswith(".")
                        or not _safe_entry(grandchild)
                    ):
                        continue
                    paths.append(grandchild.relative_to(vault_root).as_posix())
    return paths


def render_vault_map(vault_root: Path) -> str:
    lines = [HEADER.rstrip(), "", "# Vault Map", "", "Agent için yapısal giriş noktaları:", ""]
    lines.extend(f"- [[{relative}]]" for relative in _visible_paths(vault_root))
    return "\n".join(lines).rstrip() + "\n"


def _frontmatter(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    try:
        with path.open("r", encoding="utf-8") as handle:
            if handle.readline().strip() != "---":
                return values
            for line in handle:
                stripped = line.strip()
                if stripped == "---":
                    break
                key, separator, value = stripped.partition(":")
                if separator and key in {"name", "description"}:
                    values[key] = value.strip().strip('"\'')
    except (OSError, UnicodeError):
        return {}
    return values


def find_skills_dir(vault_root: Path, runtime_dir: Path | None = None) -> Path:
    vault_skills = vault_root / ".beyin" / "skills"
    if vault_skills.is_dir() and any(vault_skills.glob("*/SKILL.md")):
        return vault_skills
    if runtime_dir and (runtime_dir / "skills").is_dir():
        return runtime_dir / "skills"
    candidates = [
        Path(__file__).resolve().parent / "skills",
        Path(__file__).resolve().parent.parent / "skills",
        vault_skills,
    ]
    for cand in candidates:
        if cand.is_dir():
            return cand
    return vault_skills


def render_skills_map(vault_root: Path, runtime_dir: Path | None = None) -> str:
    lines = [
        HEADER.rstrip(),
        "",
        "# Skills Map",
        "",
        "Kanonik kaynak: `skills/`",
        "",
        "| Skill | Ne zaman kullanılır |",
        "| --- | --- |",
    ]
    skills_dir = find_skills_dir(vault_root, runtime_dir)
    for source in sorted(skills_dir.glob("*/SKILL.md")):
        values = _frontmatter(source)
        name = values.get("name", source.parent.name).replace("|", "\\|")
        description = values.get("description", "Açıklama belirtilmemiş.").replace("|", "\\|")
        lines.append(f"| `{name}` | {description} |")
    return "\n".join(lines).rstrip() + "\n"


def repair_maps(vault_root: Path, runtime_dir: Path | None = None) -> tuple[Path, Path]:
    """Self-healing generator that forcibly recreates Vault-Map and Skills-Map."""
    root = Path(vault_root)
    command_center = root / COMMAND_CENTER
    command_center.mkdir(parents=True, exist_ok=True)
    vault_map = command_center / VAULT_MAP
    skills_map = command_center / SKILLS_MAP
    _atomic_write(vault_map, render_vault_map(root))
    _atomic_write(skills_map, render_skills_map(root, runtime_dir))
    return vault_map, skills_map


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        os.chmod(temporary, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _validate_map_target(vault_root: Path, path: Path) -> None:
    if not runtime_platform.path_within_vault(path, vault_root):
        raise ValueError(f"unsafe-map-path:{path.name}")
    if path.exists() or path.is_symlink():
        if not path.is_file() or path.is_symlink():
            raise ValueError(f"unsafe-map-path:{path.name}")
        try:
            with path.open("r", encoding="utf-8") as handle:
                first_line = handle.readline()
        except (OSError, UnicodeError) as error:
            raise ValueError(f"map-collision:{path.name}") from error
        generated_headers = {HEADER}
        if LEGACY_MAP_HEADER is not None:
            generated_headers.add(LEGACY_MAP_HEADER)
        if first_line not in generated_headers:
            raise ValueError(f"map-collision:{path.name}")


def refresh_maps(vault_root: Path, max_age_seconds: float = 60.0) -> tuple[Path, Path]:
    root = Path(vault_root)
    command_center = root / COMMAND_CENTER
    vault_map = command_center / VAULT_MAP
    skills_map = command_center / SKILLS_MAP
    _validate_map_target(root, vault_map)
    _validate_map_target(root, skills_map)

    # Fast path: return existing fresh maps without filesystem traversal
    try:
        now = time.time()
        if (
            vault_map.is_file()
            and skills_map.is_file()
            and (now - vault_map.stat().st_mtime < max_age_seconds)
            and (now - skills_map.stat().st_mtime < max_age_seconds)
        ):
            try:
                with vault_map.open("r", encoding="utf-8") as h1:
                    vm_header = h1.readline()
                with skills_map.open("r", encoding="utf-8") as h2:
                    sm_header = h2.readline()
                if vm_header == HEADER and sm_header == HEADER:
                    return vault_map, skills_map
            except (OSError, UnicodeError):
                pass
    except OSError:
        pass

    _atomic_write(vault_map, render_vault_map(root))
    _atomic_write(skills_map, render_skills_map(root))
    return vault_map, skills_map


def main() -> int:
    target = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).resolve().parents[1]
    refresh_maps(target, max_age_seconds=0.0)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
